[build]
  functions = "functions"

[functions]
  # Configure external Node.js modules for Puppeteer
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

  # Set custom settings for your function (optional)
  node_bundler = "esbuild"

  # Override timeout and memory at the function level if needed
  [[functions]]
  path = "track"
  memory = 1024
  timeout = 30
