[build]
  functions = "functions"

[functions]
  # Configure external Node.js modules for Puppeteer
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

  # Use esbuild as the bundler
  node_bundler = "esbuild"

# Override memory and timeout for the specific function "track"
[functions.track]
  memory = 1024
  timeout = 30
