[build]
  command = "npm install --legacy-peer-deps"
  publish = "/opt/build/repo/public"

[functions]
  external_node_modules = [
    "chrome-aws-lambda",
    "puppeteer-core"
  ]

# Define your function here
[[functions]]
  path = "/track"
  memory = 1024
  timeout = 30
