[build]
  command = "npm install --legacy-peer-deps"
  publish = "public"

[functions]
  directory = "funtions"

  [[functions]]
    path = "/track"
    memory = 1024
    timeout = 30

  [[functions]]
    external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]
