[build]
  command = "npm install --legacy-peer-deps"
  publish = "public"  # Adjust this if your actual publish directory is different

[functions]
  directory = "funtions"  # Use the correct folder name with the typo
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

# Function-specific settings for the track function
[functions."track"]
  memory = 1024
  timeout = 30
