[build]
  command = "npm install --legacy-peer-deps"
  publish = "public" # Your publish directory

[functions]
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

[[functions]]
  path = "/track"
  memory = 1024
  timeout = 30

[[functions]]
  path = "/another-function"
  memory = 512
  timeout = 15
