[build]
  command = "npm install --legacy-peer-deps"

[functions]
  directory = "funtions"  # Your function folder name
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

# Function-specific settings for the track function
[functions."track"]
  memory = 1024
  timeout = 30
